### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dutchman71** [rzetterberg/non-crypt-hash-algorithms#1]
Hi,

I'm interested in using your hash algorithms. Can you please add a license file? Thanks!

Chris

**Comment by rzetterberg** [comment]
@dutchman71 Hello!

Cool! Added MIT-license in d6c2ca342efa5a5dea38c5364622fa7158b6349e.

Thanks for showing interest!

**Comment by dutchman71** [comment]
Thanks very much, Richard.

Chris
